[app]
title = LiveTTS Reader
package.name = livetts
package.domain = org.livetts
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,wav,json,onnx,pt,bin,token
version = 0.1.0
requirements = python3,kivy,numpy,pyjnius
orientation = portrait
fullscreen = 1
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
android.api = 33
android.minapi = 24
android.arch = arm64-v8a
android.ndk = 28c
p4a.branch = v2026.05.09
p4a.hostpython3 = python3
android.allow_backup = True
ios.kivy_ios_branch = master
